# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_foobar <- function(xp) {
    .Call('_pkg2_get_foobar', PACKAGE = 'pkg2', xp)
}

