# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

new_foobar <- function(i) {
    .Call('_pkg1_new_foobar', PACKAGE = 'pkg1', i)
}

new_foobard <- function(i) {
    .Call('_pkg1_new_foobard', PACKAGE = 'pkg1', i)
}

get_foobar <- function(xp) {
    .Call('_pkg1_get_foobar', PACKAGE = 'pkg1', xp)
}

get_foobard <- function(x) {
    .Call('_pkg1_get_foobard', PACKAGE = 'pkg1', x)
}

